version: "3.3"
services:
  database:
    image: mariadb:10.3.10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "3306:3306"
    volumes:
      - airline_database_data:/var/lib/mysql
      - ../../sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: airline
      MYSQL_USER: airline_database_admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
      - mysql_root_password

  api:
    image: airline-api:0.0.1
    depends_on:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE_HOST: database
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE: airline
      MYSQL_USER: airline_database_admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password

  web:
    image: airline-web:0.0.1
    depends_on:
      - api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  airline_database_data:
    external: true

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
